version: "3"

services:
  learn-ocaml-server:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - TZ=${TZ}
    env_file:
      - .env
    # links:
    #   - db
    #   - solr
    #   - redis
    #   - datapusher
    ports:
      - "0.0.0.0:${LEARNOCAML_PORT}:8080"
    volumes:
      - ${REPOSITORY}:/repository:ro
      - learn-ocaml-sync:/sync
    

  mongodb_container:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  nodejs:
    build: 
      context: node/
    ports: 
      - 8000:8000
    environment: 
      - 'PORT=8000'
      - 'DB_CONN=mongodb://mongodb_container:27017/learn-ocaml-code'
      - 'COMP_COLLECTION=compile-code'
      - 'EVAL_COLLECTION:eval-code'
    volumes:
      - ./node:/node/app
      - /node/app/node_modules


volumes:
  repository:
  sync:
  learn-ocaml-sync:
  mongodb_data_container:
